[package]
name = "curseforge"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
thiserror.workspace = true
serde.workspace = true
reqwest.workspace = true
tokio.workspace = true

[dev-dependencies]
dotenv.workspace = true

[lints]
workspace = true
