[workspace]
resolver = "2"
members = ["modparser"]

[workspace.dependencies]
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
tempfile = "3.10.1"

[workspace.lints.clippy]
dbg_macro = "warn"
allow_attributes = "forbid"
collection_is_never_read = "forbid"
