[workspace]
resolver = "2"
members = ["modparser", "modrinth", "mparse", "mpcli"]

[workspace.dependencies]
serde = { version = "1.0.197", features = ["derive"] }
log = "0.4.21"
thiserror = "1.0.58"
anyhow = "1.0.86"

[workspace.lints.clippy]
dbg_macro = "forbid"
allow_attributes = "forbid"
collection_is_never_read = "forbid"
module_inception = "allow"
to_string_trait_impl = "allow"
