[package]
name = "mpack"
version = "0.1.0"
edition = "2021"

[dependencies]
zip = { workspace = true, features = ["bzip2"] }
log.workspace = true
serde.workspace = true
sha1_smol.workspace = true
thiserror.workspace = true
serde_json = "1.0.120"
tempdir = "0.3.7"

[lints]
workspace = true
