[package]
name = "mpack"
version = "0.1.0"
edition = "2021"

[dependencies]
zip.workspace = true
log.workspace = true
serde.workspace = true
sha1_smol.workspace = true

[dev-dependencies]
serde_json = "1.0.120"


[lints]
workspace = true
