[package]
name = "mpcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive", "string"] }
serde_json = { version = "1.0.120" }
mparse = { path = "../mparse" }
log.workspace = true
thiserror.workspace = true
anyhow.workspace = true
fern = { version = "0.6.2", features = ["colored"] }
clap-verbosity-flag = "2.2.0"
reqwest = { version = "0.12.5", features = ["stream", "blocking"] }
indicatif = "0.17.8"


[target.'cfg(any(target_os = "windows", target_os = "macos"))'.dependencies]
dirs = "5.0.1"

[lints]
workspace = true

[features]
default = ["modrinth", "forge"]
modrinth = []
forge = []
