[package]
name = "mpcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
serde_json = { version = "1.0.120" }
mparse = { path = "../mparse" }

[lints]
workspace = true
