[package]
name = "d-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tempdir = "0.3.7"
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
mar = { path = "../mar", default-features = false, features = [
  "type-maven-artifact",
] }

[lints]
workspace = true
