[package]
name = "mparse"
version = "1.0.0"
edition = "2021"

[dependencies]
zip = { workspace = true, features = ["deflate"] }
serde.workspace = true
thiserror.workspace = true
log.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
