name: Clippy
# didnt write this btw 🤡

on:
  pull_request:
    branches: ["main"]

jobs:
  clippy:
    name: Code Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run Linter
        run: cargo clippy
          --all-features
